### PR TITLE
REL: v1.0.5

### PR DESCRIPTION
**Pull request by dmgav**

### CODE REVIEW

**Review by mrakitin — APPROVED** [review]

**Review by mrakitin — CHANGES_REQUESTED** [review]
We need those pins I mentioned earlier.

**Comment by mrakitin** [comment]
@dmgav, @tacaswell, just to be clear, is matplotlib 3.3.* completely broken for our needs? It's either 3.2 or 3.4 (that is on conda-forge now, but not in the `defaults` yet). I may need to do the same pins in the `analysis`, `nsls2-analysis`, and `collection` feedstocks.

**Review by mrakitin — APPROVED** [review]

**Comment by mrakitin** [comment]
Going to merge it now, but still waiting for your replies. I'll start that pinning now.

**Comment by dmgav** [comment]
Yes, Matplotlib 3.3 is completely broken. We can probably use 3.2, but 3.4 may work. I don't know what exactly we need to do to test it before releasing the environment. I can test it with PyXRF. May be it will cover all the issues.

**Comment by mrakitin** [comment]
Conda picked matplotlib v3.2.2 from `defaults`, so that is going to be in the conda env we deploy to the floor. I am OK with that version.

**Pull request merged**
