### PR TITLE
Rel: v1.0.0

### PR DESCRIPTION
**Pull request by dmgav**

### CODE REVIEW

**Comment by mrakitin** [comment]
There is an error in the tests:
```
ModuleNotFoundError: No module named 'pyxrf.view'
```

Is it still supposed to be there?

**Comment by dmgav** [comment]
@mrakitin Is there a way to make a list of all modules? Do we need to import all modules to test?

**Comment by dmgav** [comment]
`pyxrf.view` was deleted (enaml code)

**Comment by mrakitin** [comment]
> @mrakitin Is there a way to make a list of all modules? Do we need to import all modules to test?

Missed this question. I haven't seen it was used in conda recipes. We can run `pytest` if it covers everything and is not long to run. Or maybe a separate script (`run_tests.py`) that would contain a lighter version of imports/tests to run.

**Pull request merged**
